require('plugin.snacks')
require('plugin.everforest')
require('plugin.treesitter')
require('plugin.mini')
-- require('plugin.conform')
-- require('plugin.fidget')
require('plugin.flash')
require('plugin.lsp')
