require('plugin.everforest')
require('plugin.snacks')
require('plugin.treesitter')
require('plugin.mini')
require('plugin.autopairs')
-- require('plugin.conform')
require('plugin.fidget')
require('plugin.flash')
require('plugin.lsp')
