vim.pack.add({ 'https://github.com/folke/snacks.nvim' }, { confirm = false })
local picker_exclude = {
	'**/.git/*',
	'**/node_modules/*',
	'**/.yarn/cache/*',
	'**/.yarn/install*',
	'**/.yarn/releases/*',
	'**/.pnpm-store/*',
	'**/.idea/*',
	'**/.DS_Store',
	'build/*',
	'coverage/*',
	'dist/*',
	'hodor-types/*',
	'**/target/*',
	'**/public/*',
	'**/digest*.txt',
	'**/.node-gyp/**',
}
require('snacks').setup({
	bigfile = { enabled = true },
	-- indent = {
	-- 	enabled = true,
	-- 	animate = { duration = { step = 15, total = 300 } },
	-- },
	input = { enabled = true },
	quickfile = { enabled = true },
	-- scope = { enabled = true },
	scroll = {
		enabled = true,
		animate = { duration = { step = 6, total = 60 } },
		animate_repeat = { delay = 30, duration = { step = 3, total = 30 } },
	},
	statuscolumn = { enabled = true },
	styles = { notification = { wo = { wrap = true } } },
	words = { enabled = true },
	picker = {
		sources = {
			files = {
				hidden = false,
				ignored = false,
				win = {
					input = {
						keys = {
							['<S-h>'] = 'toggle_hidden',
							['<S-i>'] = 'toggle_ignored',
							['<S-f>'] = 'toggle_follow',
							['<C-y>'] = { 'yazi_copy_relative_path', mode = { 'n', 'i' } },
						},
					},
				},
				exclude = picker_exclude,
			},
			smart = {
				exclude = picker_exclude,
			},
			grep = {
				hidden = false,
				ignored = false,
				win = {
					input = {
						keys = {
							['<S-h>'] = 'toggle_hidden',
							['<S-i>'] = 'toggle_ignored',
							['<S-f>'] = 'toggle_follow',
						},
					},
				},
				exclude = picker_exclude,
			},
			grep_buffers = {},
			explorer = {
				hidden = true,
				ignored = true,
				supports_live = true,
				auto_close = true,
				diagnostics = true,
				diagnostics_open = false,
				focus = 'list',
				follow_file = true,
				git_status = true,
				git_status_open = false,
				git_untracked = true,
				jump = { close = true },
				tree = true,
				watch = true,
				exclude = {
					'.git',
					'.pnpm-store',
					'.venv',
					'.DS_Store',
					'**/.node-gyp/**',
				},
			},
		},
	},
})
require('core.keymap').map({
	-- Top Pickers & Explorer
	{ '<leader><space>', function() Snacks.picker.smart() end, desc = 'Smart Find Files' },
	-- { '<leader>b', function() Snacks.picker.buffers() end, desc = 'Buffers' },
	-- { '<leader>/', function() Snacks.picker.grep() end, desc = 'Grep' },
	-- { '<leader>:', function() Snacks.picker.command_history() end, desc = 'Command History' },
	-- { '<leader>n', function() Snacks.picker.notifications() end, desc = 'Notification History' },
	-- explorer
	-- { '<leader>e', function() Snacks.explorer() end, desc = 'File Explorer' },
	-- help
	-- { '<leader>h', function() Snacks.picker.help() end, desc = 'Help Pages' },
	-- find
	-- { '<leader>f', function() Snacks.picker.files() end, desc = 'Find Files' },
	-- { '<leader>fb', function() Snacks.picker.buffers() end, desc = 'Buffers' },
	-- { '<leader>fc', function() Snacks.picker.files({ cwd = vim.fn.stdpath('config') }) end, desc = 'Find Config File' },
	-- { '<leader>ff', function() Snacks.picker.files() end, desc = 'Find Files' },
	-- { '<leader>fg', function() Snacks.picker.git_files() end, desc = 'Find Git Files' },
	-- { '<leader>fp', function() Snacks.picker.projects() end, desc = 'Projects' },
	-- { '<leader>fr', function() Snacks.picker.recent() end, desc = 'Recent' },
	-- git
	-- { '<leader>gb', function() Snacks.picker.git_branches() end, desc = 'Git Branches' },
	-- { '<leader>gl', function() Snacks.picker.git_log() end, desc = 'Git Log' },
	-- { '<leader>gL', function() Snacks.picker.git_log_line() end, desc = 'Git Log Line' },
	-- { '<leader>gs', function() Snacks.picker.git_status() end, desc = 'Git Status' },
	-- { '<leader>gS', function() Snacks.picker.git_stash() end, desc = 'Git Stash' },
	-- { '<leader>gd', function() Snacks.picker.git_diff() end, desc = 'Git Diff (Hunks)' },
	-- { '<leader>gf', function() Snacks.picker.git_log_file() end, desc = 'Git Log File' },
	-- gh
	-- { '<leader>gi', function() Snacks.picker.gh_issue() end, desc = 'GitHub Issues (open)' },
	-- { '<leader>gI', function() Snacks.picker.gh_issue({ state = 'all' }) end, desc = 'GitHub Issues (all)' },
	-- { '<leader>gp', function() Snacks.picker.gh_pr() end, desc = 'GitHub Pull Requests (open)' },
	-- { '<leader>gP', function() Snacks.picker.gh_pr({ state = 'all' }) end, desc = 'GitHub Pull Requests (all)' },
	-- Grep
	-- { '<leader>sb', function() Snacks.picker.lines() end, desc = 'Buffer Lines' },
	-- { '<leader>sB', function() Snacks.picker.grep_buffers() end, desc = 'Grep Open Buffers' },
	-- { '<leader>sg', function() Snacks.picker.grep() end, desc = 'Grep' },
	-- { '<leader>sw', function() Snacks.picker.grep_word() end, desc = 'Visual selection or word', mode = { 'n', 'x' } },
	-- search
	-- { '<leader>s"', function() Snacks.picker.registers() end, desc = 'Registers' },
	-- { '<leader>s/', function() Snacks.picker.search_history() end, desc = 'Search History' },
	-- { '<leader>sa', function() Snacks.picker.autocmds() end, desc = 'Autocmds' },
	-- { '<leader>sb', function() Snacks.picker.lines() end, desc = 'Buffer Lines' },
	-- { '<leader>sc', function() Snacks.picker.command_history() end, desc = 'Command History' },
	-- { '<leader>sC', function() Snacks.picker.commands() end, desc = 'Commands' },
	{ '<leader>sd', function() Snacks.picker.diagnostics() end, desc = 'Diagnostics' },
	{ '<leader>sD', function() Snacks.picker.diagnostics_buffer() end, desc = 'Buffer Diagnostics' },
	-- { '<leader>sH', function() Snacks.picker.highlights() end, desc = 'Highlights' },
	-- { '<leader>si', function() Snacks.picker.icons() end, desc = 'Icons' },
	{ '<leader>sJ', function() Snacks.picker.jumps() end, desc = 'Jumps' },
	{ '<leader>sK', function() Snacks.picker.keymaps() end, desc = 'Keymaps' },
	{ '<leader>sL', function() Snacks.picker.loclist() end, desc = 'Location List' },
	{ '<leader>sm', function() Snacks.picker.marks() end, desc = 'Marks' },
	-- { '<leader>sM', function() Snacks.picker.man() end, desc = 'Man Pages' },
	-- { '<leader>sp', function() Snacks.picker.lazy() end, desc = 'Search for Plugin Spec' },
	{ '<leader>sq', function() Snacks.picker.qflist() end, desc = 'Quickfix List' },
	-- { '<leader>sR', function() Snacks.picker.resume() end, desc = 'Resume' },
	-- { '<leader>su', function() Snacks.picker.undo() end, desc = 'Undo History' },
	-- { '<leader>uC', function() Snacks.picker.colorschemes() end, desc = 'Colorschemes' },
	-- LSP
	-- { 'gd', function() Snacks.picker.lsp_definitions() end, desc = 'Goto Definition' },
	-- { 'gD', function() Snacks.picker.lsp_declarations() end, desc = 'Goto Declaration' },
	-- { 'gr', function() Snacks.picker.lsp_references() end, nowait = true, desc = 'References' },
	-- { 'gI', function() Snacks.picker.lsp_implementations() end, desc = 'Goto Implementation' },
	-- { 'gy', function() Snacks.picker.lsp_type_definitions() end, desc = 'Goto T[y]pe Definition' },
	-- { 'gai', function() Snacks.picker.lsp_incoming_calls() end, desc = 'C[a]lls Incoming' },
	-- { 'gao', function() Snacks.picker.lsp_outgoing_calls() end, desc = 'C[a]lls Outgoing' },
	-- { '<leader>ss', function() Snacks.picker.lsp_symbols() end, desc = 'LSP Symbols' },
	-- { '<leader>sS', function() Snacks.picker.lsp_workspace_symbols() end, desc = 'LSP Workspace Symbols' },
	-- Other
	-- { '<leader>z', function() Snacks.zen() end, desc = 'Toggle Zen Mode' },
	-- { '<leader>Z', function() Snacks.zen.zoom() end, desc = 'Toggle Zoom' },
	-- { '<leader>.', function() Snacks.scratch() end, desc = 'Toggle Scratch Buffer' },
	-- { '<leader>S', function() Snacks.scratch.select() end, desc = 'Select Scratch Buffer' },
	-- { '<leader>n', function() Snacks.notifier.show_history() end, desc = 'Notification History' },
	-- { '<leader>bd', function() Snacks.bufdelete() end, desc = 'Delete Buffer' },
	-- { '<leader>cR', function() Snacks.rename.rename_file() end, desc = 'Rename File' },
	-- { '<leader>gB', function() Snacks.gitbrowse() end, desc = 'Git Browse', mode = { 'n', 'v' } },
	{ '<leader>g', function() Snacks.lazygit() end, desc = 'Lazygit' },
	-- { '<leader>un', function() Snacks.notifier.hide() end, desc = 'Dismiss All Notifications' },
	-- { '<c-/>', function() Snacks.terminal() end, desc = 'Toggle Terminal' },
	-- { '<c-_>', function() Snacks.terminal() end, desc = 'which_key_ignore' },
	{ ']]', function() Snacks.words.jump(vim.v.count1) end, desc = 'Next Reference', mode = { 'n', 't' } },
	{ '[[', function() Snacks.words.jump(-vim.v.count1) end, desc = 'Prev Reference', mode = { 'n', 't' } },
	-- {
	-- 	'<leader>N',
	-- 	desc = 'Neovim News',
	-- 	function()
	-- 		Snacks.win({
	-- 			file = vim.api.nvim_get_runtime_file('doc/news.txt', false)[1],
	-- 			width = 0.6,
	-- 			height = 0.6,
	-- 			wo = {
	-- 				spell = false,
	-- 				wrap = false,
	-- 				signcolumn = 'yes',
	-- 				statuscolumn = ' ',
	-- 				conceallevel = 3,
	-- 			},
	-- 		})
	-- 	end,
	-- },
})
